<?php
return array (
  'embed1' => 
  array (
    'status' => '1',
    'from' => 'embed1',
    'show' => 'Dự phòng VS#1',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1003',
    'tip' => '',
    'id' => 'embed1',
  ),
  'hls1' => 
  array (
    'status' => '1',
    'from' => 'hls1',
    'show' => 'Máy chủ VS#1',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1002',
    'tip' => '',
    'id' => 'hls1',
  ),
  'embed2' => 
  array (
    'status' => '1',
    'from' => 'embed2',
    'show' => 'Dự phòng VS#2',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'embed2',
  ),
  'embed3' => 
  array (
    'status' => '1',
    'from' => 'embed3',
    'show' => 'Dự phòng VS#3',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'embed3',
  ),
  'embed4' => 
  array (
    'status' => '1',
    'from' => 'embed4',
    'show' => 'Dự phòng VS#4',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'embed4',
  ),
  'embed5' => 
  array (
    'status' => '1',
    'from' => 'embed5',
    'show' => 'Dự phòng VS#5',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'embed5',
  ),
  'embed6' => 
  array (
    'status' => '1',
    'from' => 'embed6',
    'show' => 'Dự phòng VS#6',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'embed6',
  ),
  'embed7' => 
  array (
    'status' => '1',
    'from' => 'embed7',
    'show' => 'Dự phòng TM',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'embed7',
  ),
  'hls2' => 
  array (
    'status' => '1',
    'from' => 'hls2',
    'show' => 'Máy chủ VS#2',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'hls2',
  ),
  'hls3' => 
  array (
    'status' => '1',
    'from' => 'hls3',
    'show' => 'Máy chủ VS#3',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'hls3',
  ),
  'hls4' => 
  array (
    'status' => '1',
    'from' => 'hls4',
    'show' => 'Máy chủ VS#4',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'hls4',
  ),
  'hls5' => 
  array (
    'status' => '1',
    'from' => 'hls5',
    'show' => 'Máy chủ VS#5',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'hls5',
  ),
  'hls6' => 
  array (
    'status' => '1',
    'from' => 'hls6',
    'show' => 'Máy chủ VS#6',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'hls6',
  ),
  'hls7' => 
  array (
    'status' => '1',
    'from' => 'hls7',
    'show' => 'Máy chủ TM',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'hls7',
  ),
);