<?php
return array (
  'thuongduphong2' => 
  array (
    'status' => '1',
    'from' => 'thuongduphong2',
    'show' => 'Dự phòng #2',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1003',
    'tip' => '',
    'id' => 'thuongduphong2',
  ),
  'thuong2' => 
  array (
    'status' => '1',
    'from' => 'thuong2',
    'show' => 'Máy chủ #2',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1002',
    'tip' => '',
    'id' => 'thuong2',
  ),
  'thuongduphong1' => 
  array (
    'status' => '1',
    'from' => 'thuongduphong1',
    'show' => 'Dự phòng #1',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '',
    'id' => 'thuongduphong1',
  ),
  'thuong1' => 
  array (
    'status' => '1',
    'from' => 'thuong1',
    'show' => 'Máy chủ #1',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => 'thuong1',
  ),
  'kkphim' => 
  array (
    'status' => '1',
    'from' => 'kkphim',
    'show' => 'Dự phòng [KK]',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '909',
    'tip' => '',
    'id' => 'kkphim',
  ),
  'ophim' => 
  array (
    'status' => '1',
    'from' => 'ophim',
    'show' => 'Dự phòng [OP]',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '909',
    'tip' => '',
    'id' => 'ophim',
  ),
  'thuyetminh' => 
  array (
    'status' => '1',
    'from' => 'thuyetminh',
    'show' => 'Dự phòng [Thuyết Minh]',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '909',
    'tip' => '',
    'id' => 'thuyetminh',
  ),
  'kkphimm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkphimm3u8',
    'show' => 'Máy chủ [KK]',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '',
    'id' => 'kkphimm3u8',
  ),
  'nguoncm3u8' => 
  array (
    'status' => '1',
    'from' => 'nguoncm3u8',
    'show' => 'Máy chủ [NC]',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '',
    'id' => 'nguoncm3u8',
  ),
  'ophimm3u8' => 
  array (
    'status' => '1',
    'from' => 'ophimm3u8',
    'show' => 'Máy chủ [OP]',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '',
    'id' => 'ophimm3u8',
  ),
  'thuyetminhm3u8' => 
  array (
    'status' => '1',
    'from' => 'thuyetminhm3u8',
    'show' => 'Máy chủ [Thuyết Minh]',
    'des' => 'Tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '',
    'id' => 'thuyetminhm3u8',
  ),
  'nguonc' => 
  array (
    'status' => '1',
    'from' => 'nguonc',
    'show' => 'Dự phòng [NC]',
    'des' => 'Ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '900',
    'tip' => '',
    'id' => 'nguonc',
  ),
  'vipapii' => 
  array (
    'status' => '1',
    'from' => 'vipapii',
    'show' => 'Dự phòng [VIP]',
    'des' => 'Siêu ổn định',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '101',
    'tip' => '',
    'id' => 'vipapii',
  ),
  'vipapiim3u8' => 
  array (
    'status' => '1',
    'from' => 'vipapiim3u8',
    'show' => 'Máy chủ [VIP]',
    'des' => 'Siêu tốc độ',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '100',
    'tip' => '',
    'id' => 'vipapiim3u8',
  ),
);